services:
    virtuoso:
        build:
            context: .
            dockerfile: Dockerfile.virtuoso
        environment:
            - VIRT_SPARQL_MaxQueryCostEstimationTime=default
            - VIRT_SPARQL_MaxQueryExecutionTime=300
            - VIRT_Parameters_ServerThreads=30
            - VIRT_HTTPServer_ServerThreads=300
        ports:
            - "8890:8890"
        volumes: 
            - type: volume
              source: virtuoso-db1
              target: /data
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:8890/sparql"]
            interval: 15s
            timeout: 10s
            retries: 4
volumes:
    virtuoso-db1:
