services:
    virtuoso:
        build:
            context: .
            dockerfile: ./Dockerfile.virtuoso
        environment:
            - VIRT_SPARQL_MaxQueryCostEstimationTime=default
            - VIRT_SPARQL_MaxQueryExecutionTime=300
            - VIRT_Parameters_ServerThreads=30
            - VIRT_HTTPServer_ServerThreads=300
        ports:
            - "8890:8890"
        volumes: 
            - type: volume
              source: virtuoso-db1
              target: /data
        restart: always
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:8890/sparql"]
            interval: 15s
            timeout: 10s
            retries: 4
    synbiohubFrontend:
        image: synbiohub/sbh3frontend:snapshot
        ports:
            - "3333:3333"
        labels:
            - "com.docker.desktop.open.url=http://localhost:3333"
        restart: always
        environment: 
            - backend=http://localhost:7777
            - backendSS=http://synbiohub:7777
        volumes:
          - type: bind
            source: ../synbiohub3/frontend
            target: /app
        command: ["sh", "-c", "yarn install && yarn dev"]
    synbiohub:
        # image: synbiohub/synbiohub:snapshot-standalone
        build:
            context: ./
            dockerfile: ./Dockerfile.backend
        depends_on: 
            - virtuoso
        ports:
            - "7777:7777"
        volumes:
            - type: bind
              source: ../synbiohub
              target: /synbiohub
            - type: volume
              source: sbh1
              target: /mnt
            - type: volume
              source: virtuoso-db1
              target: /virtuoso
        restart: always
        command: ["sh", "-c", "yarn install && yarn dev"]

volumes:
    virtuoso-db1:
    sbh1:
