version: '3.2'

services:
  pluginVisualSeqviz:
    image: synbiohub/plugin-visual-seqviz:snapshot
    ports:
      - "8085:5050"
    environment:
      - SEQVIZ_HOST=http://localhost:8085/
    dns:
      - 8.8.8.8
    restart: always
