version: '3.2'

services:
    pluginVisualServeTestJs:
        image: synbiohub/plugin-visual-serve-test-js:snapshot
        ports:
            - "8086:5000"
        environment:
            - SERVER_HOST=http://localhost:8086/
        restart: always
        dns: 8.8.8.8
